cabinet/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :docs

  authenticated :user do
    root "docs#index", as: "auth_root"
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cabinet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cabinet/app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user

  def self.find_docs(user)
    if Doc.exists?(user_id: user)
      Doc.where(user_id: user).order('id DESC')
    end

    Doc.all.order('id DESC')
  end
end

cabinet/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

cabinet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cabinet/app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc_by_id, only: %i[show edit update destroy]

  def index
    @docs = Doc.find_docs(current_user)
  end

  def show; end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc # does refresh
    else
      render 'new' # doesn;t refresh
    end
  end

  def edit; end

  def update
    if @doc.update(doc_params)
      redirect_to @doc # does refresh
    else
      render 'edit' # doesn;t refresh
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc_by_id
    @doc = Doc.find(params[:id])
  rescue StandardError => e
    e.error_message
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

cabinet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

cabinet/app/helpers/application_helper.rb
module ApplicationHelper
end

cabinet/app/helpers/docs_helper.rb
module DocsHelper
end

cabinet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cabinet/app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit, class: 'button'

cabinet/app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit document
  = render(:partial => "form")

cabinet/app/views/docs/index.html.haml
%h1 View All documents

.wrapper_with_padding
  #docs.clearfix
    - if not @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %h2.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(strip_tags(doc.content), length:50)
    - else
      %h2 Create Doc!
      %p Start creating new document
      %p= link_to 'Add new Doc', new_doc_path

cabinet/app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc
  = render(:partial => "form")

cabinet/app/views/docs/show.html.haml
.wrapper
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      = link_to 'View All docs', docs_path, class: 'button'
      = link_to 'Edit doc', edit_doc_path, class: 'button'
      = link_to 'Delete doc', doc_path(@doc), method: :delete, data: { confirm: "are you sure?" }, class: 'button'

cabinet/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FileCabinet | Your life's work!
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


%body
  %header
    .header_inner
      = link_to 'FileCabinet', root_path, id: 'logo'


      %nav
        - if user_signed_in?
          = link_to 'Create doc', new_doc_path
          = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          = link_to "Log in", new_user_session_path


  %p.notice= notice
  %p.alert= alert

  = yield