sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/about'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception

	def hello
		render html: '<h1>hello world!</h1>'
	end

end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home;end

  def help;end

  def about;end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title)
    content_for :title, page_title
  end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= (yield(:title)  + " - " unless yield(:title).blank?).to_s + "SampleApp" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= yield(:title) %></h1>
    <%= yield %>
  </body>
</html>

sample_app/app/views/static_pages/about.html.erb
<% page_title "About" %>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>


<%= link_to 'Home', root_url %>

sample_app/app/views/static_pages/help.html.erb
<% page_title "Help" %>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>


<%= link_to 'Home page', root_url %>

sample_app/app/views/static_pages/home.html.erb
<% page_title "Home" %>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to 'Help', static_pages_help_url %>
<%= link_to 'About', static_pages_about_url %>